import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Nabvar";
import Footer from "./component/Footer";
import AuthProvider from "./Auth/Authprovider"; 

// 🔥 ১. Toastify ইমপোর্ট করুন
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        
        <AuthProvider>
          <Navbar />
          <div className="min-h-screen">
            {children}
          </div>
          <Footer />
          
          {/* 🔥 ২. ToastContainer এখানে অ্যাড করে দিন (AuthProvider এর ভেতরে বা বাইরে সমস্যা নেই, তবে body তে থাকলেই হলো) */}
          <ToastContainer position="top-center" autoClose={3000} />
          
        </AuthProvider>

      </body>
    </html>
  );
}